/* Generated by Tessent Shell 2022.4 at Thu Mar 06 15:06:10 IST 2025 */
module counter(clk, reset, counter, ts_si, ts_so, scan_en);
  input  [0:0] ts_si;
  input  clk, reset, scan_en;
  output [3:0] counter;
  output [0:0] ts_so;

  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1, n_2, n_3, n_4, n_5, 
       n_6, n_7, n_8, ts_lockup_latchn_clkc1_intno3_, ts_pbuf_extsi4_;

  assign ts_so = ts_lockup_latchn_clkc1_intno3_;
  SDFFR_X2 \counter_up_reg[3] (
      .CK(clk), .D(n_8), .RN(n_7), .SE(scan_en), .SI(ts_pbuf_extsi4_), .Q(counter[3]), 
      .QN(UNCONNECTED)
  );
  XNOR2_X2 g84__2398(
      .A(n_6), .B(counter[3]), .ZN(n_8)
  );
  SDFFR_X2 \counter_up_reg[2] (
      .CK(clk), .D(n_5), .RN(n_7), .SE(scan_en), .SI(counter[3]), .Q(counter[2]), 
      .QN(UNCONNECTED0)
  );
  SDFFR_X2 \counter_up_reg[1] (
      .CK(clk), .D(n_4), .RN(n_7), .SE(scan_en), .SI(counter[2]), .Q(counter[1]), 
      .QN(UNCONNECTED1)
  );
  NAND2_X2 g88__5107(
      .A1(n_2), .A2(counter[2]), .ZN(n_6)
  );
  XNOR2_X2 g86__6260(
      .A(n_3), .B(counter[2]), .ZN(n_5)
  );
  AND2_X4 g90__4319(
      .A1(n_3), .A2(n_1), .ZN(n_4)
  );
  INV_X4 g89(
      .A(n_3), .ZN(n_2)
  );
  SDFFR_X2 \counter_up_reg[0] (
      .CK(clk), .D(n_0), .RN(n_7), .SE(scan_en), .SI(counter[1]), .Q(counter[0]), 
      .QN(n_0)
  );
  NAND2_X2 g93__8428(
      .A1(counter[1]), .A2(counter[0]), .ZN(n_3)
  );
  OR2_X2 g92__5526(
      .A1(counter[0]), .A2(counter[1]), .ZN(n_1)
  );
  INV_X1 g94(
      .A(reset), .ZN(n_7)
  );
  DLL_X2 ts_lockup_latchn_clkc1_intno3_i(
      .D(counter[0]), .GN(clk), .Q(ts_lockup_latchn_clkc1_intno3_)
  );
  CLKBUF_X3 tessent_persistent_cell_buf_extsi4_i(
      .A(ts_si), .Z(ts_pbuf_extsi4_)
  );
endmodule

