/* Generated by Tessent Shell 2022.4 at Wed Mar 19 11:37:00 IST 2025 */
module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o, mc_rb_fuse_vld_i, 
            mc_rb_ef1_sclk_i, SI_0, SO_0, scan_en);
  input  mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i, 
         mc_rb_ef1_sclk_i, SI_0, scan_en;
  output [4:0] skew_addr_cntr_o;
  output SO_0;

  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, 
       mc_rb_fuse_vld_q, n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8, n_9, n_10, 
       n_11, n_12, n_13, n_15, n_16, n_17, n_22, 
       ts_lockup_latchn_clkc1_intno5_, ts_pbuf_extsi6_;

  assign SO_0 = ts_lockup_latchn_clkc1_intno5_;
  SDFFR_X2 \skew_addr_cntr_reg[4] (
      .CK(mc_rb_ef1_sclk_i), .D(n_17), .RN(gctl_rclk_orst_n_i), .SE(scan_en), .SI(ts_pbuf_extsi6_), 
      .Q(skew_addr_cntr_o[4]), .QN(n_0)
  );
  AND2_X2 g405__2398(
      .A1(n_16), .A2(n_22), .ZN(n_17)
  );
  SDFFR_X1 \skew_addr_cntr_reg[3] (
      .CK(mc_rb_ef1_sclk_i), .D(n_15), .RN(gctl_rclk_orst_n_i), .SE(scan_en), .SI(skew_addr_cntr_o[4]), 
      .Q(skew_addr_cntr_o[3]), .QN(UNCONNECTED)
  );
  XOR2_X1 g407__5107(
      .A(n_12), .B(skew_addr_cntr_o[4]), .Z(n_16)
  );
  AND2_X2 g408__6260(
      .A1(n_22), .A2(n_13), .ZN(n_15)
  );
  SDFFR_X2 \skew_addr_cntr_reg[0] (
      .CK(mc_rb_ef1_sclk_i), .D(n_11), .RN(gctl_rclk_orst_n_i), .SE(scan_en), .SI(skew_addr_cntr_o[3]), 
      .Q(skew_addr_cntr_o[0]), .QN(UNCONNECTED0)
  );
  HA_X1 g409__4319(
      .A(n_6), .B(skew_addr_cntr_o[3]), .CO(n_12), .S(n_13)
  );
  SDFFR_X2 \skew_addr_cntr_reg[1] (
      .CK(mc_rb_ef1_sclk_i), .D(n_10), .RN(gctl_rclk_orst_n_i), .SE(scan_en), .SI(skew_addr_cntr_o[0]), 
      .Q(skew_addr_cntr_o[1]), .QN(UNCONNECTED1)
  );
  SDFFR_X2 \skew_addr_cntr_reg[2] (
      .CK(mc_rb_ef1_sclk_i), .D(n_9), .RN(gctl_rclk_orst_n_i), .SE(scan_en), .SI(skew_addr_cntr_o[1]), 
      .Q(skew_addr_cntr_o[2]), .QN(UNCONNECTED2)
  );
  NOR2_X2 g413__8428(
      .A1(n_8), .A2(skew_addr_cntr_o[0]), .ZN(n_11)
  );
  AND2_X2 g414__5526(
      .A1(n_22), .A2(n_5), .ZN(n_10)
  );
  AND2_X2 g415__6783(
      .A1(n_22), .A2(n_7), .ZN(n_9)
  );
  INV_X1 g417(
      .A(n_22), .ZN(n_8)
  );
  HA_X1 g416__3680(
      .A(n_4), .B(skew_addr_cntr_o[2]), .CO(n_6), .S(n_7)
  );
  HA_X1 g420__2802(
      .A(skew_addr_cntr_o[1]), .B(skew_addr_cntr_o[0]), .CO(n_4), .S(n_5)
  );
  NOR3_X2 g419__5122(
      .A1(n_1), .A2(skew_addr_cntr_o[0]), .A3(skew_addr_cntr_o[1]), .ZN(n_2)
  );
  SDFFR_X2 mc_rb_fuse_vld_q_reg(
      .CK(mc_rb_ef1_sclk_i), .D(mc_rb_fuse_vld_i), .RN(gctl_rclk_orst_n_i), .SE(scan_en), 
      .SI(skew_addr_cntr_o[2]), .Q(UNCONNECTED3), .QN(mc_rb_fuse_vld_q)
  );
  OR2_X1 g423__8246(
      .A1(skew_addr_cntr_o[2]), .A2(skew_addr_cntr_o[3]), .ZN(n_1)
  );
  OAI222_X2 g2(
      .A1(n_1), .A2(n_0), .B1(n_2), .B2(skew_addr_cntr_o[4]), .C1(mc_rb_ef1_svld_i), 
      .C2(mc_rb_fuse_vld_q), .ZN(n_22)
  );
  DLL_X2 ts_lockup_latchn_clkc1_intno5_i(
      .D(UNCONNECTED3), .GN(mc_rb_ef1_sclk_i), .Q(ts_lockup_latchn_clkc1_intno5_)
  );
  CLKBUF_X3 tessent_persistent_cell_buf_extsi6_i(
      .A(SI_0), .Z(ts_pbuf_extsi6_)
  );
endmodule

