/* Generated by Tessent Shell 2022.4 at Thu Mar 06 16:07:43 IST 2025 */
module counter(clk, reset, counter, ts_si, ts_so, scan_en);
  input  [0:0] ts_si;
  input  clk, reset, scan_en;
  output [2:0] counter;
  output [0:0] ts_so;

  wire UNCONNECTED, UNCONNECTED0, \counter[0]_19 , n_1, n_2, n_3, n_4, 
       ts_lockup_latchn_clkc1_intno2_, ts_pbuf_extsi3_;

  assign ts_so = ts_lockup_latchn_clkc1_intno2_;
  SDFFR_X1 \counter_reg[2] (
      .CK(clk), .D(n_4), .RN(n_3), .SE(scan_en), .SI(ts_pbuf_extsi3_), .Q(counter[2]), 
      .QN(UNCONNECTED)
  );
  XOR2_X1 g60__2398(
      .A(n_1), .B(counter[2]), .Z(n_4)
  );
  SDFFR_X2 \counter_reg[1] (
      .CK(clk), .D(n_2), .RN(n_3), .SE(scan_en), .SI(counter[2]), .Q(counter[1]), 
      .QN(UNCONNECTED0)
  );
  HA_X1 g62__5107(
      .A(counter[1]), .B(counter[0]), .CO(n_1), .S(n_2)
  );
  SDFFR_X2 \counter_reg[0] (
      .CK(clk), .D(\counter[0]_19 ), .RN(n_3), .SE(scan_en), .SI(counter[1]), .Q(counter[0]), 
      .QN(\counter[0]_19 )
  );
  INV_X1 g65(
      .A(reset), .ZN(n_3)
  );
  DLL_X2 ts_lockup_latchn_clkc1_intno2_i(
      .D(counter[0]), .GN(clk), .Q(ts_lockup_latchn_clkc1_intno2_)
  );
  CLKBUF_X3 tessent_persistent_cell_buf_extsi3_i(
      .A(ts_si), .Z(ts_pbuf_extsi3_)
  );
endmodule

